### ISSUE TITLE
Error relacionado con la instalación de Django

### ISSUE THREAD

**Issue by jossanrui5** [jossanrui5/EGC-830-jossanrui5#1]
Al ejecutar la aplicación, no arranca correctamente.

Para llegar a esta situación, he seguido los siguientes pasos:
1. Clonar repositorio.
2. Crear entorno virtual de python
3. Ejecutar la instrucción python ./manage.py runserver 0:8000 desde la carpeta de decide en la que se encuentra el archivo manage.py.

Devuelve la siguiente traza de error:
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Para solucionar esta situación, instalaremos django incluyendolo en el archivo requirements.txt.

**Comment by jossanrui5** [comment]
Se ha corregido el error descrito. Se ha solucionado en la rama desarrollo y se ha realizado merge a la rama master (#2 ).
